blank_issues_enabled: false
contact_links:
  - name: Questions & Support
    url: https://www.curseforge.com/wow/addons
    about: For general questions, please check the CurseForge addon page or leave a comment there.
